# Generated by Django 5.0.6 on 2024-05-22 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'admin_accounts',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('days', models.CharField(max_length=100, null=True)),
                ('time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('adminId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskManager.adminaccounts')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
