# Generated by Django 5.0.6 on 2024-05-22 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='days',
        ),
        migrations.AddField(
            model_name='task',
            name='adminId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskManager.adminaccounts'),
        ),
        migrations.AddField(
            model_name='task',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskManager.accounts'),
        ),
    ]
